GET http://localhost:4000/posts/
Authorization: Bearer eyJhbiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlUGljdHVyZSI6IiIsImZvbGxvd2VycyI6W10sImZvbGxvd2luZ3MiOltdLCJyZXB1dGF0aW9uIjowLCJfaWQiOiI2MTAzYTdmYTQ4NWE2MDFhOTg5OTFhMmEiLCJ1c2VybmFtZSI6ImxpbmgiLCJlbWFpbCI6ImxpbmhAbGluaC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRXNjlJRVZnVDR3M2lzRWgxd2VLcDRlUHBlNkdiaVVkWVFadnB2YUNjSS9oN2ZQT1VRR3Z5aSIsIl9fdiI6MCwiaWF0IjoxNjI3NzM4NTg2fQ.jw-6WovKyrG-XpAre0oZlwG-TzjalRhtXnPMNId1xwc